### PR TITLE
up support 204 with application/json header

### PR DESCRIPTION
**Pull request by rombernier**
https://github.com/SekoiaLab/platform/issues/51397

### CODE REVIEW

**Review by Darkheir — APPROVED** [review]

**Comment by rombernier** [comment]
Module Ok on test platform

**Comment by rombernier** [comment]
Hello @squioc, can you tell me when this is deployed in prod ? Thanks

**Comment by squioc** [comment]
The fix was pushed in production

**Comment by rombernier** [comment]
> The fix was pushed in production

Not yet, due to https://www.githubstatus.com/ to not forget

**Pull request merged**
