### PR TITLE
chore: move from using asset management V1 endpoints to V2

### PR DESCRIPTION
**Pull request by ysindel**
This is still a WIP, files will be changed not just renamed afterwards after validating validity of changes

### CODE REVIEW

**Comment by goudyj** [comment]
I'm really interested about this PR for a partner. Thanks @ysindel

**Comment by rombernier** [comment]
Hello @squioc, @ysindel do you have an ETA for this update on production ? Thanks

**Comment by rombernier** [comment]
Hello @squioc, @ysindel do you have an ETA for this update on production ? Thanks

**Review by squioc — APPROVED** [review]
LGTM

**Comment by rombernier** [comment]
Hello @squioc, can we deploy this in production, thanks :)

**Comment by ysindel** [comment]
hello @rombernier, I am working on merging some fixes, can you please wait for its merge

**Comment by rombernier** [comment]
Yes, of course, thanks for the update

**Pull request merged**
